---
settings:
  github_user: "jaredballou"
  github_repo: "insurgency-sourcemod"
  github_branch: "master"
  compile_plugins: true
  disable_new_plugins: true
  urls:
    'github': "https://github.com/%(github_user)s/%(github_repo)s/blob/%(github_branch)s"
    'updater': "http://ins.jballou.com/sourcemod"
paths:
  scripting: "%(root)s/scripting"
  include: "%(scripting)s/include"
  plugins: "%(root)s/plugins"
  plugins_disabled: "%(plugins)s/disabled"
  scripting_disabled: "%(scripting)s/disabled"
  scripting_outdated: "%(scripting)s/outdated"
libraries:
  ignore:
    - adminmenu
    - regex
    - sdkhooks
    - sdktools
    - sourcemod
    - updater
  thirdparty:
    - adminmenu
    - regex
    - sdkhooks
    - sdktools
    - updater
plugins:
  build:
    - ammocheck
    - botcount
    - botnames
    - botspawns
    - cooplobby
    - events
    - hlstatsx
    - insurgency
    - nofog
    - respawn
    - restrictedarea
    - rpgdrift
    - suicide_bomb
    - votelog
    - weapon_pickup
  disabled:
    - damagemod
    - cvarlist
    - dropweapon
    - insmaps
    - magnifier
    - navmesh
    - score
    - sprinklers
    - theater_reconnect
    - theaterpicker
  outdated:
    - backblast
    - navmesh-chat
    - navmesh-export
    - looting
    - noobj
    - pistolsonly
    - prop_dynamic
  thirdparty:
    - advertisements
    - afk_manager
    - clientprefs
    - gem_damage_report
    - killer_info_display
    - serverhop
    - simple-chatprocessor
    - sm_downloader
    - smtactics
    - sourcebans_listener
    - sourcebans
    - updater
    - webshortcuts
