---
libraries:
  ignore:
    - adminmenu
    - regex
    - sdkhooks
    - sdktools
    - sourcemod
    - updater
  thirdparty:
    - adminmenu
    - regex
    - sdkhooks
    - sdktools
    - updater
plugins:
  build:
    - ammocheck
    - botcount
    - botnames
    - botspawns
    - cooplobby
    - cvarlist
    - damagemod
    - dropweapon
    - events
    - hlstatsx
    - insmaps
    - insurgency
    - magnifier
    - nofog
    - respawn
    - restrictedarea
    - rpgdrift
    - score
    - sprinklers
    - suicide_bomb
    - theater_reconnect
    - theaterpicker
    - votelog
    - weapon_pickup
  disabled:
  nobuild:
    - backblast
    - navmesh-chat
    - navmesh-export
    - navmesh
    - looting
    - noobj
    - pistolsonly
    - prop_dynamic
  thirdparty:
    - advertisements
    - afk_manager
    - clientprefs
    - gem_damage_report
    - killer_info_display
    - serverhop
    - simple-chatprocessor
    - sm_downloader
    - smtactics
    - sourcebans_listener
    - sourcebans
    - updater
    - webshortcuts
